<?php if(!defined('APPLICATION')) exit();


/**
 * Constants used by Foundation Plugin.
 *
 */

// Default Configuration Settings

// Paths
define('AELIAFOUNDATION_PLUGIN_PATH', PATH_PLUGINS . '/AeliaFoundationClasses');
define('AELIAFOUNDATION_PLUGIN_VENDOR_PATH', AELIAFOUNDATION_PLUGIN_PATH . '/vendor');
define('AELIAFOUNDATION_PLUGIN_LIB_PATH', AELIAFOUNDATION_PLUGIN_PATH . '/lib');
define('AELIAFOUNDATION_PLUGIN_CLASS_PATH', AELIAFOUNDATION_PLUGIN_LIB_PATH . '/classes');
define('AELIAFOUNDATION_PLUGIN_MODEL_PATH', AELIAFOUNDATION_PLUGIN_CLASS_PATH . '/models');
define('AELIAFOUNDATION_PLUGIN_VIEWS_PATH', AELIAFOUNDATION_PLUGIN_PATH . '/views');
define('AELIAFOUNDATION_PLUGIN_OVERRIDES_PATH', AELIAFOUNDATION_PLUGIN_PATH . '/core_overrides');

// URLs
define('AELIAFOUNDATION_PLUGIN_BASE_URL', 'plugin/aeliafoundation');

define('AELIAFOUNDATION_PLUGIN_OVERRIDES_LIST_URL', AELIAFOUNDATION_PLUGIN_BASE_URL . '/overrideslist');
define('AELIAFOUNDATION_PLUGIN_GENERALSETTINGS_URL', AELIAFOUNDATION_PLUGIN_BASE_URL . '/settings');

// Return Codes
define('AELIAFOUNDATION_PLUGIN_OK', 0);

// Http Arguments
define('AELIAFOUNDATION_PLUGIN_ARG_ENABLEFLAG', 'enable');
